### ISSUE TITLE
dropLast ViewController.swift error

### ISSUE THREAD

**Issue by ghost** [cablej/Name-Picker#1]
dropLast error line 51

Not sure how to fix this. Can you please update

**Comment by cablej** [comment]
Fixed now. Was an issue with updating to Swift 2.0.

Just out of curiosity, how did you find this repo?

**Comment by ghost** [comment]
Awesome, thanks.
I work for a school district and was looking to make an app for teachers to be able to randomly select students. I don't know if this is exactly what im looking for but wanted to test out. It would be awesome if I can figure out how to allow the teachers to enter or change the names thru the app. I had an app I created a couple of years ago, but am new to swift. Need to learn.

**Comment by ghost** [comment]
Oh, and I found this repo by searching at the top.

**Comment by cablej** [comment]
This was used made for a school environment, too. The names disappear one by one until only one name remains.

Let me know if there's anything you would want added. Maybe have a second tab with a table where names can be entered and are saved? I'll also clean up this code as it was rather thrown together.
